baseurl: "/apathofbravery"
url: "https://keeftango.github.io"
collections:
  case_studies:
    output: true
    # permalink: /:path/

# baseurl: "/apathofbravery"
# url: "https://keeftango.github.io"

# For manual FTP upload
# baseurl: ""
# url: "apathofbravery.com"
# then, jekyll serve in terminal, then copy _site folder
