permalink: pretty
collections:
  case_studies:
    output: true
    # permalink: /:path/

baseurl: "/apathofbravery"
url: "http://localhost:4000"

# For manual FTP upload
# baseurl: ""
# url: "apathofbravery.com"
# then, jekyll serve in terminal, then copy _site folder
