baseurl: ""
permalink: pretty
collections:
  case_studies:
    output: true
    # permalink: /:path/

# this base url would be right if just on Github pages, breaks when connected to domain.
# baseurl: "/apathofbravery"

# For manual FTP upload
# baseurl: ""
# url: "apathofbravery.com"
# then, jekyll serve in terminal, then copy _site folder